modLoader = "javafml"
loaderVersion = "[37,)"
license = "CC0-1.0"

[[mods]]
modId = "graveyard"
version = "${version}"
displayName = "The Graveyard"
authors = "Lion"
description = '''
Adds new bosses, structures, mobs and blocks themed around the graveyard.
'''
logoFile = "graveyard_logo.png"

[[dependencies.graveyard]]
modId = "forge"
mandatory = true
versionRange = "[41.0.22,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.graveyard]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.graveyard]]
modId="geckolib"
mandatory=true
versionRange="[4.2,)"
ordering="NONE"
side="BOTH"
